import turtle
import random

win = turtle.Screen()
win.bgcolor("grey")
turtle.title("Flags Game")
t = turtle.Turtle()
t.speed(5)

points = 0
health = 3

def austria():
    t.begin_fill()
    t.color("red")
    t.fd(250)
    t.lt(90)
    t.fd(50)
    t.lt(90)
    t.fd(250)
    t.lt(90)
    t.fd(50)
    t.end_fill()

    t.color("white")
    t.fd(50)
    t.lt(90)
    t.begin_fill()
    t.fd(250)
    t.lt(90)
    t.fd(50)
    t.lt(90)
    t.fd(250)
    t.lt(90)
    t.fd(50)
    t.end_fill()
    t.begin_fill()
    t.color("red")
    t.fd(50)
    t.lt(90)
    t.fd(250)
    t.lt(90)
    t.fd(50)
    t.lt(90)
    t.fd(250)
    t.lt(90)
    t.fd(50)
    t.end_fill()

def belgium():
    t.penup()
    t.goto(-250, 0)
    t.pendown()
    t.color("black")
    t.begin_fill()
    t.forward(100)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.end_fill()
    t.penup()
    t.goto(-150, 0)
    t.pendown()
    t.color("yellow")
    t.begin_fill()
    t.forward(100)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.end_fill()
    t.penup()
    t.goto(-50, 0)
    t.pendown()
    t.color("red")
    t.begin_fill()
    t.forward(100)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.end_fill()

def estonia():
    t.pu()
    t.goto(-300, 300)
    t.pd()
    t.color("blue")
    t.goto(400, 300)
    t.begin_fill()
    t.rt(90)
    t.fd(200)
    t.rt(90)
    t.fd(700)
    t.rt(90)
    t.fd(200)
    t.rt(90)
    t.end_fill()
    t.pu()
    t.goto(-300, 100)
    t.pd()
    t.color("white")
    t.begin_fill()
    t.fd(700)
    t.rt(90)
    t.fd(200)
    t.rt(90)
    t.fd(700)
    t.rt(90)
    t.fd(200)
    t.end_fill()
    t.pu()
    t.goto(-300, -300)
    t.rt(90)
    t.color("black")
    t.pd()
    t.goto(400, -300)
    t.begin_fill()
    t.goto(400, -300)
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(700)
    t.lt(90)
    t.fd(200)
    t.end_fill()

def france():
    t.color("blue")
    t.begin_fill()
    t.forward(100)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.end_fill()
    t.penup()
    t.goto(100, 0)
    t.pendown()
    t.color("white")
    t.begin_fill()
    t.forward(100)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.end_fill()
    t.penup()
    t.goto(200, 0)
    t.pendown()
    t.color("red")
    t.begin_fill()
    t.forward(100)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.end_fill()

def germany():
    t.goto(40, 30)
    t.color("black")
    t.begin_fill()
    t.fd(200)
    t.bk(400)
    t.rt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.end_fill()
    t.pu()
    t.rt(180)
    t.fd(100)
    t.pd()
    t.color("red")
    t.begin_fill()
    t.fd(100)
    t.rt(90)
    t.fd(400)
    t.rt(90)
    t.fd(100)
    t.end_fill()
    t.pu()
    t.lt(180)
    t.fd(100)
    t.color("yellow")
    t.begin_fill()
    t.pd()
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.end_fill()
    t.pu()

def italy():
    t.begin_fill()
    t.color("green")
    t.fd(100)
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(200)
    t.end_fill()
    t.lt(90)
    t.fd(100)

    t.begin_fill()
    t.color("white")
    t.fd(100)
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(200)
    t.end_fill()
    t.lt(90)
    t.fd(100)

    t.begin_fill()
    t.color("red")
    t.fd(100)
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(200)
    t.end_fill()

def poland():
    t.color("white")
    t.begin_fill()
    t.goto(0, 75)
    t.fd(100)
    t.rt(90)
    t.fd(75)
    t.rt(90)
    t.fd(200)
    t.rt(90)
    t.fd(75)
    t.rt(90)
    t.fd(100)
    t.end_fill()
    t.pu()
    t.color("red")
    t.begin_fill()
    t.goto(0, 0)
    t.pd()
    t.fd(100)
    t.rt(90)
    t.fd(75)
    t.rt(90)
    t.fd(200)
    t.rt(90)
    t.fd(75)
    t.rt(90)
    t.fd(100)
    t.end_fill()

def sweden():
    t.pu()
    t.color("blue")
    t.goto(-200, 300)
    t.pd()
    t.begin_fill()
    t.fd(200)
    t.rt(90)
    t.fd(120)
    t.rt(90)
    t.fd(200)
    t.rt(90)
    t.fd(120)
    t.rt(90)
    t.fd(200)
    t.end_fill()
    t.color("yellow")
    t.begin_fill()
    t.pu()
    t.goto(-110, 300)
    t.pd()
    t.rt(90)
    t.fd(120)
    t.rt(90)
    t.fd(30)
    t.rt(90)
    t.fd(120)
    t.rt(90)
    t.fd(30)
    t.end_fill()
    t.begin_fill()
    t.pu()
    t.goto(-200, 250)
    t.pd()
    t.fd(200)
    t.rt(90)
    t.fd(30)
    t.rt(90)
    t.fd(200)
    t.rt(90)
    t.fd(30)
    t.end_fill()

def greece():
    t.speed(5)
    t.penup()
    t.goto(-180, 120)
    t.pendown()

    stripe_height = 20
    for i in range(9):
        t.begin_fill()
        if i % 2 == 0:
            t.fillcolor("blue")
        else:
            t.fillcolor("white")
        for _ in range(2):
            t.forward(320)
            t.right(90)
            t.forward(stripe_height)
            t.right(90)
        t.end_fill()
        t.penup()
        t.right(90)
        t.forward(stripe_height)
        t.left(90)
        t.pendown()

    t.penup()
    t.goto(-180, 120)
    t.pendown()
    t.begin_fill()
    t.fillcolor("blue")
    for _ in range(2):
        t.forward(120)
        t.right(90)
        t.forward(80)
        t.right(90)
    t.end_fill()

    t.color("white")
    t.penup()
    t.goto(-180 + 60, 120)
    t.setheading(-90)
    t.pendown()
    t.pensize(8)
    t.forward(80)

    t.penup()
    t.goto(-180, 120 - 40)
    t.setheading(0)
    t.pendown()
    t.forward(120)

def netherlands():
    t.begin_fill()
    t.color("red")
    t.fd(250)
    t.lt(90)
    t.fd(50)
    t.lt(90)
    t.fd(250)
    t.lt(90)
    t.fd(50)
    t.end_fill()

    t.color("white")
    t.fd(50)
    t.lt(90)
    t.begin_fill()
    t.fd(250)
    t.lt(90)
    t.fd(50)
    t.lt(90)
    t.fd(250)
    t.lt(90)
    t.fd(50)
    t.end_fill()
    t.begin_fill()

    t.color("blue")
    t.fd(50)
    t.lt(90)
    t.fd(250)
    t.lt(90)
    t.fd(50)
    t.lt(90)
    t.fd(250)
    t.lt(90)
    t.fd(50)
    t.end_fill()

guala = [austria, belgium, estonia, france, germany, italy, poland, sweden, greece, netherlands]

while len(guala) != 0 and health >= 1:
    t.reset() # katharizei tin othoni, epistrefei tin xelona sto kentro (0,0) kai koitaei pros ta deksia
    flag = random.choice(guala) # mia tyxaia epilogi apo ti lista guala
    flag()
    answer = input("Which flag is this? ")
    if answer.lower() == flag.__name__: # .lower() -> kanei mikra ta grammata tis synartiseis, __name__ -> pairnei to onoma tis synartiseis
        print("That's right!")
        points += 1
        print("Points:", points)
        guala.remove(flag) # vgazei ti shmaia apo ti guala an apantisw swsta
    else:
        health -= 1
        print("Wrong!")
        print("Lives:", health)

    if health == 0:
        t.reset()
        t.color("red")
        t.write("You lost!", align = "center", font = ("Tahoma", 30, "bold"))
        t.hideturtle()

    ''' if health == 0:
            break '''

if len(guala) == 0:
    t.reset()
    t.color("red")
    t.write("Congratulations! You won!", align = "center", font = ("Tahoma", 30, "bold"))
    t.hideturtle()

turtle.done()